hpcc-systems/hpcc4j

- org.hpccsystems.rdf.rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
> HPCC-JAPIs-59 Fetch info from first dropzone available

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCECLDirectClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsSQLClient.java
> HPCC-JAPIs-62 Add support for custom ports

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> HPCC-JAPIs-67 Proposed solution for archived WU results

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
> HPCC-JAPIs Add new line when closing multipart

- org.hpccsystems.ws.client/pom.xml
> HPCC-JAPIs-72 Add javax.mail maven dep

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/utils/Sftp.java
> HPCC-JAPIs-70 Report all errors via exception

- org.hpccsystems.rdf.rdf2hpcc/pom.xml
- org.hpccsystems.ws.client/pom.xml
- pom.xml
> HPCC-JAPIs-76 Update rdf tool deps

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsSQLClient.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/platform/Workunit.java
Signed-off-by: rpastrana <rpastrana@lexisnexis.com>
> JAPI-2 Changes required for JDBC integration

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> Additional method to get workunits by WUQuery, for more flexibility in searching workunits.

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsSQLClient.java
> JAPI-3 Check ECL and ESP exceptions after WsSQL executes and prepare

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/platform/DataSingleton.java
- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/platform/Version.java
> remove overrides

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
> JAPI-10 Add sprayXML helper functions

- org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- org.hpccsystems.ws.client/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
> HPCC-JAPI-11 Stop Using ECLDirect, use WSWU instead

- clienttools/pom.xml
- pom.xml
- rdf2hpcc/pom.xml
- wsclient/pom.xml
Bringing project inline with: http://semver.org/
JAPI-13
> Introducing Semantic Versioning to 0.6 branch

- clienttools/pom.xml
- pom.xml
- rdf2hpcc/pom.xml
> JAPI-18 Add Maven deploy to all poms

- clienttools/pom.xml
- pom.xml
- rdf2hpcc/pom.xml
- wsclient/pom.xml
> JAPI-21 Update POMs to http://mvnrisk.risk.regn.net/nexus

- clienttools/pom.xml
- pom.xml
- rdf2hpcc/pom.xml
- wsclient/pom.xml
> JAPI-21 Add maven-release-plugin to poms

- clienttools/pom.xml
- pom.xml
- rdf2hpcc/pom.xml
- rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
- wsclient/pom.xml
> JAPI-26 Update new mvnrisk repo url yet again!

- rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDF2HPCC.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
> JAPI-32 WsClient Connection fix, default RDF2HPCC values

- wsclient/src/main/java/org/hpccsystems/ws/client/gen/wsworkunits/v1_56/WURun.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/wsworkunits/v1_56/WsWorkunitsLocator.java
> JAPI-41 Add WuRun update to wsworkunits generated code

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
Fixes JAPI-42. Take a look and let me know if this is the right way to fix it.
> Check for errors in submitted workunit before running

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> JAPI-47 Make createAndRunWUFromECL public

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> JAPI-46 Changes to WUQuery

- pom.xml
- wsclient/pom.xml
> Version changes for 0.6.5

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCv500/antlr/EclRecord.g4
- wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecord.g4
- wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecordReader.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnAnnotation.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnInfo.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java
This is in addition to the work that Luke Renn did for handling annotations embedded within comments.  I added multi line comment annotations and the appropriate test methods.
@rpastrana please review
> JAPI-39 Annotation changes in grammar

- wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecordReader.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java
Let me know if you want this PR to a different branch.
> Add annotations to fields, not records.

- pom.xml
- wsclient/pom.xml
> Versioning for v0.6.6 updating master

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClientPool.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/ObjectPool.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
> JAPI-38 Provide HPCC WsClient Pooling

- pom.xml
- wsclient/pom.xml
> JAPI 0.6.8 version changes in pom

- clienttools/README.md
- rdf2hpcc/README.md
- wsclient/README.md
> Readme changes for maven dependencies

- wsclient/README.md
- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> JAPI-73 WUAction backwards compatiblity with 5 series ESPs

- docs/common/Version.xml.in
Fix JAPI-75 DOCS:Build Components
Update the doc build components
used for building the JAPI docs.
Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@rpastrana please review
> JAPI-75 DOCS:Build Components

- docs/JAPI_doc/Japi_Mods/Japi_Use.xml
Fix JAPI-55 DOCS:Build Workflow
Updated Japi doc - Use Cases section.
Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@Michael-Gardner  please review
> JAPI-55 DOCS:Build Workflow

- docs/CMakeLists.txt
> JAPI Versioning for docs before 1.0.0 tag

- docs/JAPI_doc/Japi_Mods/Japi_Build.xml
- docs/JAPI_doc/Japi_Mods/Japi_Use.xml
> JAPI-76 Move Maven dep to build from use cases

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
I have added an upload method using NIO library, which also implements specified landing zone.
> Method to upload for Mini-Apps

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> Include Wuid in parameters sent to createAndUpdate

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
> JAPI-78 Cosmetic changes to uploadLargeFile

- wsclient/README.md
- wsclient/pom.xml
> wsclient-1.0.4 versioning and changelog

- rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
- Utilizes wsfsclient get dropzones
> JAPI-72 Correctly use WsClient WsFS methods

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- wsclient/README.md
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Workunit.java
- wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientTest.java
Perhaps not the best fix, but if for some reason the WS doesn’t return the state ID, but does return the state name, allow these methods to work and not throw an NPE.  This previously happened when checking an archived work unit.
> JAPI-83: StateID from State only.

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- wsclient/README.md
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/WUState.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Workunit.java
- [X ] This change is a bug fix (non-breaking change which fixes an issue).
- [ X] I have created a corresponding JIRA ticket for this submission
- [ X] My code follows the code style of this project.
- [ X] I have applied the Eclipse code-format template provided.
- [ X] The change has been fully tested:
- [ X] I have performed unit tests to cover my changes.
- [ X] I have performed system test and covered possible regressions and side effects.
- [ X] I have checked that this change does not introduce memory leaks.
- [ X] Scalability
- [ X] Performance
- [ X] Security
- [ X] Thread-safety
- [ X] Premature optimization
- [ X] Existing deployed queries will not be broken
- [ X] This change fixes the problem, not just the symptom
- [ X] The target branch of this pull request is appropriate …
> JAPI-81 add Paused enum value to WUState

- wsclient/pom.xml
- updates jsch dep 0.1.51 -> 0.1.54
> JAPI-86 Update JCRAFT JSCH library to avoid connect issue

- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsSQLClient.java
> JAPI-87 Update wssql interface in HPCCWsSQLClient

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DropZone.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
> JAPI-80 Changes for dropzones with new hostname/address combinations

- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
> Japi-90, createOrUpdate method

- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ECLAttributeInfo.java
* add DeleteModule and DeleteAttribute to the HPCCWsAttributesClient class.
* add ECLAttributeInfo wrapper class
* update findItems() to return List<ECLAttributeInfo> rather than ECLAttribute[]
* update handleExceptions to additionally set the message of the wrapping exception to the content of the ArrayOfEspException exceptions
> JAPI-95: wrap attribute delete calls

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFULogicalFileInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUResult.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
* add searchFiles() and deleteFiles() methods to HPCCWSDFUClient
* they return soap-version-agnostic DFULogicalFileInfo and DFUResult wrapper pojos 
* updated getFiles() and getLogicalFiles() to also return the wrapper class
* updated handleException to add the concatenated errors of the ArrayOfEspException exceptions to the  (currently null) base exception message
* updated the HIPIE hpcc connection unit test to call and verify all of the above
> Japi-97 : new dfu methods

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ClusterInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/QueryFileInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/QueryResult.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/QuerySetFilterType.java
* add additional methods for querying/updating roxie services to HPCCWsWorkunitsClient to avoid calls to underlying soap services from HIPIE . New methods return soap-version-agnostic POJOS
* tested all new methods via the HIPIE HPCC unit tests
> Japi-98 : additional HPCCWsWorkunitsClient methods for roxie services

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ApplicationValueInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/WorkunitInfo.java
Integrating this with HIPIE and testing I found a bug in ApplicationValueInfo, and also found I'd forgotten to add a setNamedValues() that takes NamedValue[] array . I missed this in the workunit changes pr. These changes were tested via HIPIE.
> JAPI-99 : add setter for NamedValue[] for backward compatibility

- wsclient/README.md
- Adds release dates
- Organizes released versions and future releases
> JAPI update changelog

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFilePartInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFilePartsOnClusterInfo.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
Modified FileDetailInfo class to produce a by cluster array of File Part metadata containers.
Added a wrapper class for the cluster file part metadata container.
Added a wrapper class for the file part metadata.
Added logic to PlatformTester class to show file part information for one of the test files.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
- [x ] This change is a new feature (non-breaking change which adds functionality).
- [x ] I have created a corresponding JIRA ticket for this submission
- [x ] My code follows the code style of this project.
- [x ] I have applied the Eclipse code-format template provided.
- [x ] I have read the HPCC Systems CONTRIBUTORS document (https://github.com/hpcc-systems/HPCC-Platform/wiki/Guide-for-contributors).
- [ x] I have performed unit …
> JAPI-00096 Expose file part information

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ClusterInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/QueryResult.java
- wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientIntegrationTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/IntegrationTest.java
Fix NPE in SearchQueries.
Add an integration test to test this, and update the pom.xml to exclude integration tests when "mvn install" is called.
> Fixes for japi - 102

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/QueryResult.java
> Japi-108 : null check when creating queryresult object

- wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsAttributesClientIntegrationTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsWorkunitsClientIntegrationTest.java
- Organizes imports in test client integration classes
> JAPI-111 Remove java8 dependancies

- wsclient/pom.xml
> JAPI 2.0.0 Snapshot for 7.0 interface

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
Add parameters to request file structure information to HPCCWsDFUClient.
Add new fields and missing fields to copy function in DFUFileDetailInfo class.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
File structure information retrieve from files residing on the ML Dev cluster.
> JAPI-00109 File Structure info

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
- Adds iscompressed to object copy
> JAPI-118 Address missing DFUFileDetail field

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
> JAPI-115 Check for null returns in DFUFileDetailInfo toString method

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
- Adds user to platform hash value
> JAPI-121 Platform hash should include user

- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Uses password regex pattern
- Adds new lines to single line usage string
> JAPI-129 Platform tester fixes

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Added downloadFile API
- Added downloadFile test
> JAPI-127 Add FileSpray/DownloadFile to JAPI

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
- Provides new constructor based on java.net.URL styled url string
- Provides toString()
> JAPI-134 New Utils.connection constructor

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/DropZone.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/LogicalFile.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/PhysicalFile.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/PhysicalMachine.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Reflects new DZ/machines/files structure
- Adds new helper methods
- Adds sample test cases
> JAPI-117 Restructure dropzone representation

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
- Added check to prevent null ptr exception
> JAPI-136: Connection constructor exception without query param

- wsclient/README.md
- wsclient/pom.xml
> Wsclient changelog 7.0.2 1

- wsclient/pom.xml
I ran the wsclient unit and integration tests after making this change.
I also built the jar and used it in HIPIE, running a regression test that walked all the files on a cluster and attempted to load their ecl layouts, to see if any new and unexpected errors occur with 4.7 that didn't with 4.5.  Everything looks good.
> Japi-140 update antlrversion

- wsclient/README.md
> 1.6.0 README UPDATE

- wsclient/README.md
> UPDATE MASTER README

- eclipse/HPCC-JAVA-Formatter.xml
- Applies various code format improvements
> JAPI-141 JAPI eclipse based formatter update

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/WUActionCode.java
- wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientTest.java
- Add WUAction enum
- Interrogate WU actionex and action
> JAPI-92 Consider original WU action when determining completeness

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCECLDirectClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Replaces direct soapaccess null tests with function call
> JAPI-135 Standardize soapproxy access within wsclient code

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> JAPI-146 Build break from conflict merge error

- README.md
> Introduce commons-hpcc link to README file

- commons-hpcc/pom.xml
- commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/RecordDefinitionTests.java
> JAPI-148 Address build break related to commons project

- commons-hpcc/pom.xml
> JAPI-149 Add Developers section to commons project pom

- README.md
> Add dfsclient to JAPI readme

- dfsclient/pom.xml
> DFS initial release pom changes

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/TestFieldDefinitions.java
> JAPI-150: Add missing file

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/TestRecordReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/RemoteTests.java
> JAPI-150 Added missing file

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRecordAccessor.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/IRecordAccessor.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/ReflectionRecordBuilder.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadTest.java
- Return "this" object in setter methods
- Adds method chaining test
> JAPI-155 DFSClient Method chaining

- dfsclient/pom.xml
> dfsclient-7.0.10-SNAPSHOT pom update

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- Utilize java.arrays function to copy byte array
- Add junit
> JAPI-144 wsfileio array copy enhancement

- wsclient/src/test/java/org/hpccsystems/ws/client/RemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- Refactors remotetests to remotetest
> JAPI-157 Address missing remotetest definition

- wsclient/pom.xml
> JAPI-153 Using pom exclusion technique

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUCreateFileWrapper.java
- Adds 7.2 createfile
- Adds DFUFileAccessInfoWrapper getter
Signed-off-by: Pastrana <PastraRX@RISK.REGN.NET>
> JAPI-160 Add missing wsclient methods in 7.2

- dfsclient/pom.xml
> Dfsclient poms wsclient version changed to 7.2.0

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
Tested with a 215mb file and the full file was transfered, before you only got 16384 bytes of the file (16*buffer).
> JAPI-163- HPCCFileSprayClient largeFileUpload truncated files at 16384 bytes

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- Changed SecAccessType from Full to Read in 7.0 code path to fix getFileAccess issues
> JAPI-161 HpccWsDFUClient.getFileAccess fails against HPCC 7.0.X

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileTypeWrapper.java
- Adds new methods which expose previously hidden options
- Adds wrapper around wsdfu filetype enum
Signed-off-by: Pastrana <PastraRX@RISK.REGN.NET>
> JAPI-166 Expose all 7.2+ WSDFU create file options

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
> JAPI 164 Re-introduce legacy wswu 1.56 and 1.69 interfaces

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ECLResultInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/WorkunitInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/ApplicationValueWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/DebugValueWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/WUExceptionWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUCreateFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLGraphWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLHelpFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLQueryWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLSourceFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLTimingDataWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLWorkflowWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ThorLogInfoWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateAndUpdateWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoDetailsRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUUpdateRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUUpdateResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientSoapProxyWrapper.java
Signed-off-by: Pastrana <PastraRX@RISK.REGN.NET>
> JAPI-159 Replace wswu1.73 with wsws1.74

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Interpret 401 message from wssmc
- Throw exception when getHPCCBuild fails
- Handle cases where Version is not available
Signed-off-by: Pastrana <PastraRX@RISK.REGN.NET>
> JAPI-165 Handle HPCC Version fetch failure

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/ECLResultInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/WorkunitInfo.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/ApplicationValueWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/DebugValueWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/WUExceptionWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUCreateFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileTypeWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLGraphWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLHelpFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLQueryWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLSourceFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLTimingDataWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLWorkflowWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ThorLogInfoWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateAndUpdateWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoDetailsRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUUpdateRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUUpdateResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientSoapProxyWrapper.java
> JAPI-167 BinaryRecordWriter is not casting Integer types correctly

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Passes along original exception message
> JAPI-139 RefreshWU to retain original exception message

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
I didn't.  I just added the cause to the exception.
> JAPI-168 Proper exception handling.  Preserve the cause.

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
> JAPI-169: Better error reporting on failed upload.

- wsclient/pom.xml
- wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsAttributesClientIntegrationTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsWorkunitsClientIntegrationTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsAttributesClientIntegrationTest_620.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsWorkunitsClientIntegrationTest_54.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsWorkunitsClientIntegrationTest_620.java
- Provides baseremotetest abstract class
- Remote tests now extend baseremotest
- Connection to hpcc defaults to localhost:8010 no creds
- Connection and creds provided via java env props
-- Via Maven: mvn -DargLine="-Dhpccconnect=http://ip:8010 -Dhpccuser=user -Dhpccpass=pass -Dlzname=someip" install
-- Via Eclipse: VM Args in run profile: -Dhpccconnect=http://ip:8010 -Dhpccuser=user -Dhpccpass=pass -Dlzname=someip
> JAPI-147 Centralize remote test connection options gathering

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Pom update for master (7.2.2, 1.0.6)

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Pinned versions for gold 7.2.0.1

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Pinning versions to gold 7.2.0.1

- commons-hpcc/src/main/java/org/hpccsystems/commons/network/Network.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/network/NetworkTests.java
- Adds ipv4/6 islocaladdress methods
- Provides list of all local (non-loopback addresses)
- Provides JUNIT tests
> JAPI-175 Adds local address support to commons-hpcc

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Prioritizes file part copies based on locality
> JAPI-176 DFSCLIENT exploit potential file part copy locality

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- Handles ESP exceptions even if no file access info provided
> JAPI-170 Improve WsDFU file access error reporting

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> JAPI-172 DFSClient: Fixed length strings are set to null

- commons-hpcc/pom.xml
> JAPI-179 Adds missing log4j dependancy

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> JAPI-182 Enable SNAPSHOT fetches from oss repository

- dfsclient/pom.xml
- Updates pom.xml to declare log4j 1.2.17 dep
> JAPI-180 DFSClient log4j dependancy matches wsclient

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- Bails out if wsdfuclient init failed
- Provides error details
> JAPI-171 Improve creatfileparts error case

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCECLDirectClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Addresses several javadoc errors
- Adds missing javadoc content
> JAPI-183 Update wsclient javadoc content

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Pom Update: wsclient, dfsclient 7.2.6, commons-hpcc 1.0.6

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- Allow ECL unsigned value to overflow in JAVA
> JAPI-191 Do not report error java unsiged overflow

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldDef.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/RecordDefinitionTranslator.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- Added code to keep track of flags on Record fields
- Modified RecordDefinitionTranslator to setAdditionalFlags and use additional flags when generating JSON record defs
- Improved exception messages to make actual errors more evident
> JAPI-178 DFSClient: Null pointer exception when reading some key files

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
> JAPI-186 Reject reading non-Flat files

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> Japi-194: allow override of default connect timeout

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Synchronize file part copy index access
- Declare filepartcopy in req json structure
> JAPI-188 Declare file part copy index upon initial dafiserv request

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> JAPI 7.2.14 Gold

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
- dfsclient 7.2.18-SNAPSHOT
- wsclient 7.2.18-SNAPSHOT
- commons 1.0.14-SNAPSHOT
> JAPI update master poms

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Migrates concept of init error to wswuclient
- Generates hash based on initerror if necessary
> JAPI-200 Handle case where WsXXXClient doesn't initialize

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Gold release 7.2.16 pom updates

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- wsclient/pom.xml
> Master update 7.4.0 snapshot

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> JAPI-204 Support query limit in DFSCLIENT

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldFilterRange.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FileFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLExpression.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLFragment.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLOperator.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLTable.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/FilterTests.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-152 Update ECL Filter classes

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-206 Fix Invalid SQL syntax in filtered test case

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
> JAPI-210 Remove flat file read restriction

- dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/wsdfu/v1_50/DFUFileType.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/wsdfu/v1_51/DFUFileType.java
> JAPI-212 DFSClient must provide fileread kind

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientSoapProxyWrapper.java
> JAPI-213 Update WsWU use174 method

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
> HPCC-JAPI-214 Add useSSL option to RowServiceOutputStream

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileTypeWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-209 Override DFUFileType comparison logic

- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-216 Fix DFU Filetype Test case issue

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RFCCodes.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
> JAPI-211 Translate DFSERR codes

- dfsclient/.classpath
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-224 DFSCLIENT should report new japi 7.6 exceptions

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
> JAPI-229 Fix build break in dfsclient

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/PhysicalMachine.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLResultWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WorkunitWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
> JAPI-230: final axis2 refactoring for salt/hpcc use of wsclient

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
> JAPI-232: update baseremotetest, missed in last PR

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
> JAPI-231 Provide spray status mehanism

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUQueryWrapper.java
Fix NPEs occurring in WUQueryWrapper and CompileWUFromEcl.
Tested by running mvn test on HPCC-JAPIS and running through the unit tests and integration tests for the tardis hpcc module and dependent projects.
> Japi-242 and Japi-241 : NPE Fixes

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- pom.xml
- wsclient/pom.xml
> JAPI-245 Top Level Pom Deployment Fix

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLSourceFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUCreateAndUpdateWrapper.java
Tested with mvn test and by running through all unit & integratio tests for our projects that use hpcc-japis; and also by firing up hipie, web services and dsp-next and putting them through their paces.
> JAPI-246 and JAPI 244 -NPE fixes and wsattributesclient fix

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
Got further with my integration testing with the previous batch of NPE fixes, and triggered this one:
> JAPI-256 - more NPE fixes

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/ESPExceptionsTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/IntegrationTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/ManualUnitTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSTopologyClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
> Japi 252 junitimprove

- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/CryptoHelper.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/DigestAlgorithmType.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/CryptoHelperTest.java
- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- Adds commons/utils CryptoHelper
- Adds set/fetch encrypted wsstore calls
- Adds junit test cases
> JAPI-248 Provide crypto support

- wsclient/pom.xml
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
> JAPI-253 Address lost change causing buid break

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoResponseWrapper.java
> Japi 254 - WUInfoResponseWrapper fix NPE for deleted workunit

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/DataSingleton.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsAttributesClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsSMCClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Deprecates STATIC WSDL URL methods
- Create new properly named methods
- Provide current connection URL methods
Signed-off-by: Pastrana, Rodrigo <915949+rpastrana@users.noreply.github.com>
> JAPI-257 Prevent improper use of ORIGINALWSDL URL

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FileFilter.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/FilterTests.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- Stops wrapping JSON array in curly
- camelCase keyFilter name
- Updates JUnit
> JAPI-260 Fix keyfilter syntax issues

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
I've used this code to remove package parts across different clusters and targets.
Followed the same pattern as the other methods in this class.
> JAPI-259 RemovePartFromPackageMap support.

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldDef.java
> JAPI-265 FieldDef toString

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- Also provide ECL to describe default files
> JAPI-266 Add default hpcc file and superfile names

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-262 Remove cluster param from wsdfu::deletefile

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FileFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/network/Network.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/CryptoHelper.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
- pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecordReader.java
- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/PhysicalMachine.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Sftp.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
> JAPI-268: Address potential log4j security issue

- dfsclient/pom.xml
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSBenchmarkTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added read benchmark unit tests for different data types. Benchmark tests fail if read performance is lower than 90% of raw socket performance.
> JAPI-237: Create benchmark unit tests

- commons-hpcc/src/main/java/org/hpccsystems/commons/network/Network.java
> JAPI-268: Fix

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java
> JAPI-268 Fix

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/IWsWorkunitsClientStubWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStub1_58.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStub1_62.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStub1_69.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStub1_75.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStubWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
> JAPI-256 Refactor to not cache stubs (from Luke Renn)

- commons-hpcc/pom.xml
- dfsclient/pom.xml
- pom.xml
- wsclient/pom.xml
> JAPI-236 added go_gold and go_snapshot tagging and branch creation scripts

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
…background thread
- Added in prefetching to RowServiceInputStream
- Improved string construction improvements in BinaryRecordReader
- Reduced amout of data copying during record construction in BinaryRecordReader
> JAPI-240: DFSClient: RowServiceInputStream should prefetch data

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
Submitting this as it's needed for HIPIE capabilities.
Tested with unit tests, also tested end-to-end by pointing HIPIE at the new method and running tests.
> JAPI-273: new searchFiles method

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
Signed-off-by: Rodrigo <rodrigo.pastrana@lexisnexisrisk.com>
> JAPI-272 Handle empty physical file array scenario

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
- wsclient/src/test/resources/filespraytest/Japi274deleteDropzoneFileTest.csv
Created unit tests to first upload a file to the landing zone and then delete that file from the landing zone.
> Implement function to delete file from a drop zone

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
Created a unit test; also reran DFUReadWriteTest.
> Japi-278 handle npes in RowServiceInputStream

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> Japi 279 use reponse wrapper

- pom.xml
> JAPI-281 Don't skip deployment

- wsclient/pom.xml
> JAPI-xxx Add exclusions for remote tests by default

- dfsclient/pom.xml
- wsclient/pom.xml
> JAPI-283 Use project.version to simplify dependency versions

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Update JUnit tests to use the correct datasets
> JAPI-290 DFSClient: Correct JUnit test dataset names

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsAttributesClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsWorkunitsClientIntegrationTest_54.java
> Japi 288 address several junit

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoRequestWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
> JAPI-289 new getWUInfo method

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WUInfoRequestWrapper.java
Fix line endings in WUInfoRequestWrapper
> line ending fix

- pom.xml
- wsclient/src/main/resources/log4j2.xml
- wsclient/src/test/java/org/hpccsystems/ws/client/LoggerManagerTest.java
> JAPI-287 Provide basic log4j2 config for development

- dfsclient/pom.xml
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSBenchmarkTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/RemoteTests.java
- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/RemoteTests.java
> Japi 291 remote test interface

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileDetailWrapper.java
> JAPI-294 : add getClusters method

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileDetailWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-296 : adding unittest for new getclusters method

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSPackageProcessTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java
- Ensures single setup per junit class
- Fixes several format issues
- Declares setup method as static due to @beforeclass annotation
- Ensures Objects are tested for null before referencing
- Expands junit coverage
- Declares assumptions in order to invalidate tests
> JAPI-301 Address several Junit issues

- wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java
> JAPI-300 Ingores non generic junit test

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSBenchmarkTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-295 DFSClient: Add support for writing udecimals and qstr to HPCC

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
> JAPI-306 JUnit Test Failure Fix

- docs/CMakeLists.txt
Successful Unit testing: http://10.240.61.86/view/JavaProjects/job/JAPI-Docs-7.8.x/
> JAPI-308 Set StageVer value for Doc build

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
> JAPI-247 Ensures Booleans are not null before referencing

- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
> JAPI-307 Junit comparison should ignore capitalization

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> JAPI-313 Add FileSprayClient.renameLogicalFile()

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
Created unit test to test retrieving metadata for a file that exists and a file that does not exist.
Also tested compiled dfsclient jar with the tardis hpcc module and confirmed it works.
> Japi-320 add getOriginalFileMetadata() to HPCCFile

- dfsclient/pom.xml
- dfsclient/src/main/java-templates/CompileTimeConstants.java
- pom.xml
> JAPI-304 Implement templating for benchmarking logic

- pom.xml
> hpcc4j-322 Fix Javadoc error when using jdk8 style and jdk11/12 javadoc

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/AddtoSuperfileRequestWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/AddtoSuperfileResponseWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/ArrayOfEspExceptionWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/EspExceptionWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/EspSoapFaultWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/ExceptionsWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsdfu/SubfileNames_type0Wrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-324 Add createsuperfile support

- pom.xml
> JAPI-305 Automate non-snapshot release process on sonatype

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-328 Change RowServiceInputStream to default to handle usage

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/StreamOperationMessages.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Provide stream operation message class
- Store messages in hashmap, keyed on message type, message and target column
- Report summary of messages upon completion of operation
> JAPI-326 Summarize read operation messages

- docs/CMakeLists.txt
> hpcc4j-333 Generate doc version from top level pom

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
> JAPI-331 Avoid NP references in WsWUclient

- pom.xml
> hpcc4j-337 Updating junit version from 4.12 to 4.13.1

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
Tested writing a BigDecimal UNSIGNED8 value and reading it back out to verify it was the same.
Also tested externally with the tardis Hpcc module.
> hpcc4j-339 : handle writing BigDecimal INTEGER fields

- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/UtilsTests.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- Provide utility to convert u8 from long to BigInt
> JAPI-327 Unsinged8 helper method

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Version.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/WsDFUClientStubWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStubWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/VersionTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Improve parse logic
- Provide Junit test cases
> JAPI-336 Update platform.Version logic

- dfsclient/README.md
> Update dfsclient Readme

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/RecordDefinitionTranslator.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRecord.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java
- Added support for writing fixed length data fields
- Fixed HPCCRecord comparison of byte arrays
- Corrected record translation to maintain fixed length field types
> JAPI-342 Can't write DATAXX fields with dfsclient

- dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/StreamOperationMessages.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/ECLSourceFileWrapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStubWrapper.java
> hpcc4j-312 Manually fix javadoc errors and warnings

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsworkunits/WsWorkunitsClientStubWrapper.java
> HPCC4J-344 Addresses minor merge issue

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Version.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/VersionTest.java
> HPCC4J-346 Version should account for large seq number and tag postfix

- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFilePartWrapper.java
> hpcc4j-353 DFU filepart should provide tlk flag

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldDef.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldFilterRange.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FileFilter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/CompiledFieldFilter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java
- Added partition processor that can use TLK information to filter out partitions
- Changed WSDfuClient code to maintain TLK partitions
- Added partition filtering method to HPCCFile
> JAPI-329 Utilize TLK during index read

- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLFilter.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLFragment.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLOperator.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/FilterTests.java
- Acknowledge double quote as rcpression boundary
- Do not trim content of literal
- Provide various tests
> HPCC4J-352 SQLExpression logic update

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Version.java
> HPCC4J-355 Remove superflous version ctr output

- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> HPCC4J-362 Fix DFU Junit test expecting failure

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
- Expose thor/roxie cluster and filegroup variables
-
> HPCC4J-354 Improve JUNIT Base class

- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Fixed partition processor handling of single files
- Updated DFSIndexTest to also handle single file parts correctly
> JAPI-363 PartitionProcessor fails with single file part files

- dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileTypeWrapper.java
- Updated DataPartition.FileType to encompass new file types
- Updated translation code to make missing file type support easier to spot
> JAPI-364 handle new INDEXLOCAL filetype enum

- dfsclient/src/main/java-templates/CompileTimeConstants.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- pom.xml
- Move compiletimeconstants class to named package (org.hpccsystems.generated)
> HPCC4J-360 Update CompileTimeConstants package name

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-361 Ability to "restart" a file read

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Axis2ADBStubWrapperMaker.java
- Updated Axis2ADBStubWrapper to load classes from a jar
> JAPI-349 Wrapper generator tool does not load classes within jars

- dfsclient/pom.xml
- dfsclient/src/main/java/org/hpccsystems/dfs/client/AvroGenericRecordAccessor.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/AvroRecordTranslator.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/AvroSchemaTranslator.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/ParquetInputFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/ParquetOutputFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSAvroTranslationTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSParquetReadWriteTest.java
- pom.xml
- Added avro core as dependency
- Created avro schema to hpcc record def translator
- Created avro filed to hpcc filed translator
- Created avro translation unit tests
- Created example code using avro translation support to read avro & parquet files
> JAPI-317 Support reading of parquet files

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSPackageProcessTest.java
- Add addpackage,deletepackage generic helper methods
- Add corresponding Junit
> JAPI-374 Expand WsPackageProcessClient support

- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-368 Removes unreliable junit condition

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/TestRecordReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Platform.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/Workunit.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexisrisk.com>
> hpcc4j-358 Fixed deprecated Constructors

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/DelimitedDataOptions.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> Japi-375 Enhance HPCCFileSprayClient

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-372 DFSclient remote tests taking too long

- wsclient/src/test/java/org/hpccsystems/ws/client/WSPackageProcessTest.java
- Empty list response is valid
- Add/delete based on wildcard
- Wrapped/non-wrapped specific packages
> JAPI-380 Address several wsPackageProcess Junit failures

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
> HPCC4J-386 Add HPCCFile.setFilter(FileFilter)

- .github/workflows/remoteUnitTests.yml
> RemoteUnitTests github action to 7.12.x branch

- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> HPCC4J-392 FileSprayJunit prereq

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/ECLAttributeWrapper.java
- wsclient/src/test/java/org/hpccsystems/ws/client/DFUFileDetailWrapperTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java
> JAPI-396 Remove apache.commons.lang3

- .github/workflows/remoteUnitTests.yml
> Pin hpccsystemslegacy/platform to 7.12.32-1 tag for remoteUnitTests workflow

- docs/HPCC4J_doc/HPCC4J_Mods/HPCC4J_Intro.xml
- docs/HPCC4J_doc/HPCC4J_Mods/HPCC4J_Use.xml
Signed-off-by: g-pan <greg.panagiotatos@lexisnexis.com>
@rpastrana or @jpmcmu please review. 
Provided PDF Proof separately 
locally built PDF provided separately
> JAPI-390 Add JAVA over TLS notice to doc

- .github/workflows/javadocTest.yml
> HPCC4J-402 Javadoc Test Workflow

- dfsclient/README.md
> HPCC4J-369 Add DFSClient Avro support blurb

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-376 Introduce forced timeout junit tests for DFUClient reads/writes

- pom.xml
Bumps commons-io from 2.4 to 2.7.
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Bump commons-io from 2.4 to 2.7 (#483)

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Fixed issue with out of bounds issue in getResumeInfo
- Added unit test for resume functionality
> JAPI-408 Address array out of bounds in DFSclient stream restart

- pom.xml
> JAPI-409 commons-io dependency is only used in test

- pom.xml
> JAPI-410 Remove xml encoded chars

- pom.xml
> JAPI-414 Exclude WSDLs and log4j deps

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
> JAPI-413 Properly map 7+ WsDFU requests

- wsclient/src/test/resources/generatedata.sh
> HPCC4J-418 Add generatedata.sh to wsclient test resources

- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> JAPI-423 Provide Verify localhost method for WsFileSpray HTTPS junit

- .github/workflows/https-environment.xml
- .github/workflows/httpsUnitTests.yml
> HPCC4J-391 Enable https for testing

- commons-hpcc/src/main/java/org/hpccsystems/commons/errors/WUException.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Introduce WUException
- Report WUID within exception
> HPCC4J-426 Report failed WUID

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- Maps OS value from response to request
- Appends / to path
> JAPI-428 ESP 8.2.2+ uploadfile changes

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> JAPI-422 DFSclient should always specify file type

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRandomAccessFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUXRefClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsResourcesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
> HPCC4J-425 Fix javadoc errors thrown with javadoc 8 seriesh

- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> JAPI-433 Allow selfsigned localhost https

- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- Modified how partition processor treats TLKs with a single range
> JAPI-429 DFSClient fails to read keys with no TLK partition

- rdf2hpcc/pom.xml
- rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
> JAPI-431 Changes required for Jena update

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Axis2ADBStubWrapperMaker.java
> HPCC4J-442 Replace tab chars with 4 spaces in generated wrappers

- commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldFilterRange.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLExpression.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLFragment.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/filter/SQLOperator.java
- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/UtilsTests.java
- commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/FilterTests.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> HPCC4J-445 Add Junit tests for date tests

- pom.xml
Bumps log4j-core from 2.13.2 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
> Bump log4j-core from 2.13.2 to 2.15.0

- README.md
> HPCC4J-446 Disclose log4j vulnerability

- README.md
> HPCC4J-466 Log4J disclosure

- pom.xml
Bumps log4j-core from 2.15.0 to 2.16.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Bump log4j-core from 2.15.0 to 2.16.0 (#522)

- pom.xml
Bumps log4j-core from 2.16.0 to 2.17.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Bump log4j-core from 2.16.0 to 2.17.0 (#528)

- pom.xml
Bumps log4j-core from 2.17.0 to 2.17.1.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Bump log4j-core from 2.17.0 to 2.17.1 (#533)

- dfsclient/src/main/java/org/hpccsystems/dfs/client/CompiledFieldFilter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Fixed off by one error where first partition range was not created
- Added log message for invalid filters
> JAPI-437 TLK Indexes not filtering partitions as expected

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/CompiledFieldFilter.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRecord.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- Changed how partition processor creates the cap record in TLKs
> JAPI-440 Process valid TLKs - currently dropping "empty" TLKs

- .github/workflows/httpsUnitTests.yml
> HPCC4J-448 Specify localhost SAN in system test certs

- pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCPreemptiveAuthInterceptor.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java
> HPCC4J-447 Update Axis2 1.8.0

- README.md
> HPCC4J-451 Announce axis2 version related issue

- README.md
> HPCC4J-451 Announce axis2 version related issue (#541)

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
> JAPI-458 : New search files method using wrapper

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
- Creates new enumeration
- Adds new method which accepts enum and sets text value to requeswrapper
> HPCC4J-459 Provide DFUQUERY.filetype enumeration

- .github/workflows/JAPIPRBuildAction.yml
- .github/workflows/httpsUnitTests.yml
- .github/workflows/remoteUnitTests.yml
> HPCC4J-441 Add rebases to pull request builds

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- Sets XML Doc builder/parser secure values
> JAPI-461 Do not resolve XML external entities

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
> HPCC4J-467 Provide empty creds object when necessary

- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/CryptoHelper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- Defaults to AES cipher
- Removes encryptSHA512AESPKCS5Pad methods
> HPCC4J-464 Obsolete use of weak AES/ECB/PKCS5PADDING cipher

- pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
> HPCC4J-469 Update Axis2 dependancy

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-465 DFSIndexTest/DFSReadWriteTest - Implicit narrowing conversion issue

- wsclient/src/test/java/org/hpccsystems/ws/client/security/XMLParsing.java
- wsclient/src/test/resources/security/externalentity.xml
- wsclient/src/test/resources/security/localfile.xml
- wsclient/src/test/resources/security/localfilexxe.xml
- wsclient/src/test/resources/security/millionlaughs.xml
- wsclient/src/test/resources/security/xxe.xml
- Creates XML parsing exploit tests
> HPCC4J-468 Security exploit junit tests

- .github/workflows/JAPIPRBuildAction.yml
- .github/workflows/httpsUnitTests.yml
- .github/workflows/remoteUnitTests.yml
> HPCC4J-466 Add development name/email to git config inside container

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
> HPCC4J-472 Remove use of NamedValue in favor of NamedValueWrapper

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/PartitionProcessor.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Modified binary record reader to correctly read indexes
> JAPI-470 DFSClient: Index field types handled incorrectly

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRandomAccessFileReader.java
- Correced issue wehere HpccRandomAccessFileReader did not handle index differences
> JAPI-475 DFSClient: Random Access reader index bias

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Disabled random batch access until the cause of the test failure can be identified
> JAPI-476 intermittent DFSClient TLK filter JUNIT test failure

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
> Japi 484 download authorized

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsCodeSignClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUXRefClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsPackageProcessClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsResourcesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSMCClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/extended/HPCCWsAttributesClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSCodeSignClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSPackageProcessTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSResroucesClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSTopologyClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsAttributesClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUXRefClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsSMCClientTest.java
- Adds mechanism to fetch continerized mode from target HPCC
- Adds isContainerized member to basewsclient
- Removes baseWSClient dependance on implementation
> HPCC4J-486 Provide target HPCC containerized mode status

- wsclient/pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsCloudClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/ArrayOfEspException.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/EspException.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/EspSoapFault.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/Exceptions.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/ExtensionMapper.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/GetPODsRequest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/GetPODsResponse.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/String.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/WsCloud.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/WsCloudPingRequest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/WsCloudPingResponse.java
- wsclient/src/main/java/org/hpccsystems/ws/client/gen/axis2/wscloud/latest/WsCloudStub.java
- wsclient/src/main/resources/WSDLs/WsCloud.wsdl
- wsclient/src/test/java/org/hpccsystems/ws/client/WSCloudClientTest.java
- Adds WsCloud WSDL
- Adds Axis2 generated stub and corresponding mvn profile
- Adds corresponding junit
> HPCC4J-487 Add support for WsCloud

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUXRefClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/HpccContainerizedUnsupportedException.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSTopologyClientTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUXRefClientTest.java
- Rejects invalid containerized requests
- Updates junit tests
> HPCC4J-478 Invalidate baremetal specific functionality

- commons-hpcc/src/main/java/org/hpccsystems/commons/utils/Utils.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added flag to support treating U8s as BigDecimals
- Created JUnit for U8 to Decimal
> JAPI-499 BinaryRecordReader support U8 to Decimal

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added string processing flags / code in BinaryRecordReader
- Implemented unit tests for trim / empty to null conversion
> JAPI-500 String trim flag when reading hpcc files

- rdf2hpcc/pom.xml
- rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
- Updates wsclient dep to cve patched version
- Updates target java version
- Updates wsclient API references
> HPCC4J-502 Update RDF2HPCC deps

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
> JAPI-503 String processing JUnit failure

- .github/workflows/publish-snapshots-on-merge.yml
- Creates action to publish snapshots
> HPCC4J-505 Github Action publish snapshots

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
> JAPI-507 DFSClient: Add support for new rowservice protocol

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added check for EOS characters within strings to BinaryRecordWriter
- Created unit test to check EOS issue
> DFSClient: File corruption if strings include EOS character

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Axis2ADBStubWrapperMaker.java
- Uses simple class name to determine match
> HPCC4J-508 WrapperMaker use simple class name

- dfsclient/pom.xml
- pom.xml
> JAPI-496 Create File Utility, POM Changes

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java
- Synchronizes xml parse calls
- Adds corresponding junit tests
> HPCC4J-513 Protect javax.xml.parsers.DocumentBuilder Parse calls

- .vscode/launch.json
- wsclient/pom.xml
- wsclient/utils/README.md
- wsclient/utils/wsInterfaceUpdater.py
- Adds python to generate new wsdls, stub, and wrappers
- Adds vscode launch profile
> HPCC4J-334 Automate WsClient Interface

- wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java
> HPCC4J-514 WUQueryTest Ensures multiple WUs available

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java
- Added additional Real type conversions
> JAPI-519 DFSClient: BinaryRecordWriter improve float conversions

- .github/workflows/publish-snapshots-on-merge.yml
> HPCC4J-522 GithutAction targets java8

- .github/workflows/BuildTestCandidateAndMaster.yml
- .github/workflows/JAPIPRBuildAction.yml
- .github/workflows/Nightly.yml
- .github/workflows/httpsUnitTests.yml
- .github/workflows/javadocTest.yml
- pom.xml
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Updated POM file to use release configuration
> HPCC4J-523 Incorrect Java version linking based on JDK

- .github/workflows/publish-snapshots-on-merge.yml
extend action to on branch creations as well
> Update publish-snapshots-on-merge.yml (#617)

- .github/workflows/publish-release-on-merge.yml
- Added a new github action workflow to publish builds on release tag
> HPCC4J-501 Deploy artifacts via github action

- .github/workflows/publish-snapshots-on-merge.yml
> JAPI-501 Disable snapshot publish on release tag

- .github/workflows/Jirabot.yml
- Added logic to translate hpcc4j prefix
> HPCC4J-532 Jirabot should translate hpcc4j prefix

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
- Added missing @return annotation
> HPCC4J-536 Fix WSClient javadoc warning

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Fixed status mapping
- Improved code flow
- Improved issue commenting
- Moved issue update to separate function
> HPCC4J-532 Jirabot python script fixes

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Disabled empty compressed file test
> HPCC4J-543 Empty compressed file test failure

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Updated jirabot merge script to trigger on PR close instead of push
- Fixed transition message on transition failure
> HPCC4J-532 Jirabot python scripts

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Moved JiraURL to vars
- Added mising import for errors
> HPCC4J-532 Jirabot fixes

- .github/workflows/JirabotMerge.yml
> HPCC4J-532 Extends print statement

- dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Added an option to HPCCFile to make TLK reading optional
> HPCC4J-551 HPCCFile Make TLK Use Optional

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- Re-enabled tests that are now passing
> HPCC4J-511 Test failures in containerized environment

- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Modified HPCCRemoteFileReader to enforce consistent early close behavior
- Added unit test to ensure consistent behavior on early close
- Minor changes to exception handling
> HPCC4J-556: File Reader Early Close Behavior

- pom.xml
> HPCC4J-557 Bump hadoop dep to 3.3.6

- .github/workflows/httpsUnitTests.yml
- Changed Helm command to use Helm HPCC version instead of latest
> HPCC4J-558 Github Actions: Outdated HPCC Version

- dfsclient/pom.xml
- pom.xml
- wsclient/pom.xml
> HPCC4J-555 POM Fixes

- pom.xml
> HPCC4J-564 Bump org.json version to 20231013

- .github/workflows/JirabotMerge.yml
> HPCC4J-571 Github Action: Jirabot Merge fails to find tag

- .github/workflows/publish-snapshots-on-merge.yml
- Updated development JDK env to 11 to meet 9+ req.
> HPCC4J-580 Github Actions Snapshot publish fails

- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- dfsclient/src/test/resources/generate-datasets.ecl
- Added additional datasets to read / write integration tests
> HPCC4J-584 Add XML,CSV,JSON read write tests

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
- wsclient/src/test/java/org/hpccsystems/ws/client/utils/UtilsTest.java
- Introduces functionality to strip trailing white space
- Adds trimright utility functionality
- Adds new test cases
- Adjusts pre-existing test cases to expected | actual format
- Do not trim original string parameter
- Do not duplicate Path URL param
> HPCC4J-581 WsFS Client should add path delim only if needed (#690)

- .github/workflows/Jirabot.yml
- Updated Jirabot to use Atlassian python library
- Updated Jirabot to leave a comment on the Github PR
> HPCC4J-574 Jirabot Improvements

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Updated jirabot merge script to use Atlassian python library
- Updated project name in JirabotMerge and Jirabot
> HPCC4J-593 Update JirabotMerge for Jira Cloud

- pom.xml
- Updated hadoop client version
> HPCC4J-565 Bump hadoop-client lib version

- .github/workflows/baremetal-regression-suite.yml
- Added a manual call to setupPKI
> HPCC4J-600 Bare metal github action breaking dafilesrv certs unavailable

- pom.xml
> HPCC4J Fix pom mismerge MASTER

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Fixed jirabot merge add fix version code
- Updated transition logic to be less brittle
> HPCC4J-608 Merge fix version failure

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added code read the rowservice handle before closing sockets when hitting EOF
> HPCC4J-622 RowserviceInputStream read handle during close

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Fixed syntax error due to missing change
> HPCC4J-608 JirabotMerge: Fixed syntax error

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
> HPCC4J-623 Need to read addl int before close()

- pom.xml
> HPCC4J-632 Add OTLP Exporter dep

- .github/workflows/JirabotMerge.yml
- Improved tag filtering to find fix versions to support more complex tag structures
> HPCC4J-638 Jirabot Merge improve tag regex filtering

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added mising param description
> HPCC4J-635 Fixed javadoc comment

- dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
- Added FileUtility options: ignore_tlk, read_retries,socket_time_seconds,filter
> HPCC4J-645 FileUtility filtering support and testing improvements

- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Moved log prefix construction in available into closed block
> HPCC4J-648 RowServiceInputStream available log prefix into closed block

- pom.xml
> HPCC4J-XXX Pom upmerge issue fix 9.6->9.8

- pom.xml
- Upgraded commons-io to new version
- Add version overrides for Axis2 deps with vulnerabilities
> HPCC4J-658 Upgrade out-of-date dependencies

- pom.xml
> HPCC4J-660 Upgrade out-of-date Axis2 dependencies

- .github/workflows/javadocTest.yml
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccRDD.java
> HPCC4J-670 Fix workflow issues pertaining to spark-hpcc migration

- .github/workflows/baremetal-regression-suite.yml
- Removed the set-output action from our github actions
> HPCC4J-674 Removed deprecated feature from GithubAction

- .github/workflows/JirabotMerge.yml
- Updated out of date actions
- Moved to using more secure ENV variables to echo Github variables
- Fixed project prefix comparison
> HPCC4J-676 Migrate Jirabot Improvements

- .github/workflows/publish-release-on-merge.yml
- .github/workflows/publish-snapshots-on-merge.yml
- Updated deployment action to skip integration tests
> HPCC4J-678 Deployment action should skip integration tests

- .github/workflows/publish-release-on-merge.yml
- .github/workflows/publish-snapshots-on-merge.yml
> HPCC4J-678 Deployment action should skip integration tests 

- spark-hpcc/pom.xml
- Updated Spark-HPCC pom to use toplevel pom profile configuration
- Removed contact info for previous developer
> HPCC4J-682 Spark-HPCC Release workflow broken

- .github/workflows/BuildTestCandidateAndMaster.yml
- .github/workflows/baremetal-regression-suite.yml
> HPCC4J-683 Update github action cache plugin to v3

- pom.xml
- Updates avro dep to 1.12.0 to avoid CVEs
> HPCC4J-684 Address Avro CVEs

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Fixed potential issue where reading long null terminated strings can cause misalignment within the read stream
- Fixed an issue with QStrings where buffer stalls during reading can cause misalignments
- Cleaned up null terminated string reading
- Added check for max string length
> HPCC4J-693 DFSClient: Issue reading long null terminated strings

- .github/workflows/baremetal-regression-suite.yml
- .github/workflows/k8s-regression-suite.yml
- pom.xml
- spark-hpcc/pom.xml
- spark-hpcc/src/test/java/org/hpccsystems/spark/BaseIntegrationTest.java
- wsclient/pom.xml
> HPCC4J-697 Update Spark Tests for HPCC4j Repo 

- .github/workflows/JAPIPRBuildAction.yml
- .github/workflows/baremetal-regression-suite.yml
- .github/workflows/javadocTest.yml
- .github/workflows/k8s-regression-suite.yml
- Changed maven test settings to continue on failure
- Added python script to process failures and add an error annotation
> HPCC4J-690 Github tests should continue on failure

- pom.xml
- spark-hpcc/pom.xml
- wsclient/pom.xml
> HPCC4J-701 Upmerge missing pom changes

- pom.xml
> HPCC4J-704 Address cve-2025-30065

- pom.xml
> HPCC4J Address cve-2025-30065

- .github/workflows/Jirabot.yml
- Updated Jirabot to use Ubuntu 24.04 to fix deprecation of 20.04 in GHub actions
> HPCC4J-707 Update Jirabot to use Ubuntu 24.04

- wsclient/src/test/java/org/hpccsystems/ws/client/TestResultNotifier.java
- Modified TestResultNotifier to escape CSV output for newlines and double quotes
> HPCC4J-706 TestResultNotifier should escape CSV output

- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java
- wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java
- Utilizes wssmc ping
- Avoids possible null response
> HPCC4J-705 Avoid lengthy server ping

- dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added tracing to deserialization code paths / record construction
> HPCC4J-703 DFSClient: Add tracing on deserialization code paths

- wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- Updates invalidtable fetch expectation
- Updates get all tables test expectation
> HPCC4J-712 Update HPCCWsSQLClient test

- wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- Adds method to deteremine target HPCC auth mode
- Fetches auth mode in wsstore client tests suite
- Avoids non-global tests if not auth
> HPCC4J-659 Avoids non-global wsstore tests if no authentication

- spark-hpcc/Examples/PySparkExample.ipynb
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccFile.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccRDD.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- Added option to read specific file parts to Spark options
- Added additional logging information on file part read start / stop
> HPCC4J-698 Spark should allow reading particular file parts

- .github/workflows/baremetal-regression-suite.yml
- .github/workflows/k8s-regression-suite.yml
- spark-hpcc/pom.xml
- Added TestResultNotifier to Spark-HPCC project
- Updated workflows to check for Spark failedTests.csv
> HPCC4J-699 Spark-HPCC test suite needs to generate FailedTests file

- .github/workflows/baremetal-regression-suite.yml
> HPCC4J-633 Add secured HPCC deployment to automated test environment

- .github/workflows/baremetal-regression-suite.yml
- wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- Changed test credentials to be randomly generated
- Modified WSStoreClientTest to use randomly generated test credentials
> HPCC4J-633 Add secured deployment to automated test env

- .github/workflows/publish-snapshots-on-merge.yml
> HPCC4J-720 Provide central portal snapshot server-id

- wsclient/src/main/java/org/hpccsystems/ws/client/utils/ConnectionTester.java
> HPCC4J-726 Provide simple connection test app

- .github/workflows/javadocTest.yml
> HPCC4J-729 Avoid mvn install on javadoc building github action

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/build-k8s/action.yaml
- .github/actions/deploy-hpcc-k8s/action.yaml
- .github/workflows/build-docker.yml
- .github/workflows/k8s-regression-suite.yml
- Added support for testing against specific repositories / branches in the K8s test
repository: hpcc-systems/HPCC-Platform
branch: candidate-9.6.x
> HPCC4J-730 K8s testing against target branches

- .github/workflows/upmerge-comment.yml
- .github/workflows/upmerge-test.yml
- Fixed issue with setting the maven version
- Added input validation from the upmerge-test step
> HPCC4J-656 Upmerge comment action master

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/build-k8s/action.yaml
- .github/actions/deploy-hpcc-k8s/action.yaml
- .github/workflows/build-docker.yml
- .github/workflows/k8s-regression-suite.yml
- Added support for testing against specific repositories / branches in the K8s test
> HPCC4J-730 K8s testing against target branches 9.10.x

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/build-k8s/action.yaml
- .github/actions/deploy-hpcc-k8s/action.yaml
- .github/workflows/build-docker.yml
- .github/workflows/k8s-regression-suite.yml
- Added support for testing against specific repositories / branches in the K8s test
> HPCC4J-730 K8s testing against target branches 9.8.x

- .github/workflows/baremetal-regression-suite.yml
- .github/workflows/k8s-regression-suite.yml
- Fixed baremetal image URLs
- Added hpcc-systems as a default allowed repo to K8s scripts
- Changed repo matching logic to be case insensitive
repository: 
branch:
> HPCC4J-731 Baremetal tests unable to find platform images

- pom.xml
- Addresses security issues in Parquet Avro 1.15.1
repository: 
branch:
> HPCC4J-736 Upgrade Parquet Avro Dependency

- spark-hpcc/Examples/PySparkExample.ipynb
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccFile.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccRDD.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- spark-hpcc/src/test/java/org/hpccsystems/spark/DataframeIntegrationTest.java
- Exposed string processing flags to Spark
- Added information on string processing to Spark example notebook / documentation
repository: 
branch:
> HPCC4J-735 Allow string trimming

- .github/workflows/JirabotMerge.yml
> HPCC4J-738 Jirabot Atlassian library breaks Python 3.8 compat

- spark-hpcc/Examples/PySparkExample.ipynb
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccFile.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/HpccRDD.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- spark-hpcc/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- Added an option to the Spark read function to map Unsigned8 to Decimal
- Updated Spark examples / documentation
repository: 
branch:
> HPCC4J-743 Spark: Expose Unsigned8 to Decimal option

- .github/copilot-instructions.md
> HPCC4J-744 Create copilot instructions
