README.md, org.hpccsystems.ws.client/pom.xml, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/utils/Sftp.java, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, org.hpccsystems.ws.client/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Add JSCH dependancy
- Add SFTP utility class
- Implement SFTP to HPCC Landing Zone method
- Add new helper methods in filespray which utilze sftp to upload files
- Add new helper method in wsclient to make use of filespray methods
- Updated README
=> HPCC-JAPIs-61 Implement SFTP stop using WS to upload files

org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/platform/WorkunitInfo.java
add check in getWUInfo to un-archive a workunit if it's archived before returning
add getWUResults to retrieve a workunit result
add espURL for external reference to track where a WorkunitInfo came from. (Rodrigo, there may be a better place to get this from than parsing the soap endpoint string, let me know.)
=> Support retrieving results, etc. from archived workunits

org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, org.hpccsystems.ws.client/src/main/java/org/hpccsystems/ws/client/utils/FileFormat.java
Since ESP aliases the CSV data format flag for ASCII, the client should do the same to prevent further confusion.
Also, add new method with default values for formattype=ASCII, maxsize= 8192 and rowtag = "tag"
=> JAPI-10 ESP uses "csv" as an alias for ASCII encoding

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnInfo.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
for #99, Added two new wrapper classes for the ajax-generated DFUDataColumn and DFUFileDetail classes,  DFUDataColumnInfo and DFUFileDetailInfo.
Moved the calculation of the file type & file fields into DFUFileDetailInfo.
=> Refactoring changes to support returning child dataset info from HPCCWsDFUClient.getDatasetFields

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/FileFormat.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- move "sprayvariable" format enum to spray client code
- create new fileformat enum and helper w/ flat,csv,xml,json
- add sample use in test code
=> JAPI-17 Clean up fileformat enum

rdf2hpcc/pom.xml, rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDF2HPCC.java, rdf2hpcc/src/main/java/org/hpccsystems/rdf/rdf2hpcc/RDFHPCCWsClient.java
* Updated POM to require wsclient 0.6.2 for utils.Connection fix
* Added -eclstatsfile flag to allow for user defined ecl
* Hard-coded STATSECL is still default for reporting
* Fixed issue with required parameters not actually being required, and
causing null ptr exceptions later on in the import phase of rdf2hpcc
=> JAPI-5 Added feature to allow user defined ecl file for stats

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java
Don't fail if only warnings exist in the Workunit eclexceptions collection.
For https://track.hpccsystems.com/browse/JAPI-44
=> Filter to actual errors

wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecord.g4, wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecordReader.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnAnnotation.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnInfo.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java
Fixes https://track.hpccsystems.com/browse/JAPI-54
* Support annotations with no parameters, e.g. // @FEW
* Support multiple annotations per field, e.g. // @FEW, @METATYPE(SSN)
* Support annotations for Records, e.g. RECORD //@RECORDCOUNT(100000000)
* Add annotations to toString() method
* Add tests for the above to DFUFileDetailInfoTest and run test
I built the wsclient jar and ran the HIPIE junit tests for metatype annotations to confirm everything still works.
=> issue #54 enhanced annotations

wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java
@rpastrana I reviewed all the other possible issues in this file.  This is the one change that was necessary to fix the null ptr exception without screwing up the logic.  The way we discussed earlier isn't possible because the file type can still be null and we can derive the file type from other attributes that are set.
=> JAPI-50 Fixed Null Ptr Exception in DFUFileDetailInfo

wsclient/src/main/java/org/hpccsystems/ws/client/platform/Workunit.java, wsclient/src/test/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClientTest.java
New JUNIT test.  Run against HIPIE wsclient tests.
We're going to need this ASAP, so if you want to create a new branch (1.2.1 or something) I can resubmit there.  The Enums should be changed to have state (for their ids) and use `.valueOf` instead of the map, but I'm not going to introduce such a change in this PR.
=> JAPI-91 Fix COMPILING state map.

wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecord.g4, wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java
Updated the antlr grammar for ecl record parsing, and added a unit test to test the change.  All unit tests for record parsing still work.
Also tested via HIPIE to verify that the original issue (reading in salt record layouts containing maxlength fields) was resolved.
=> japi-107 - update antlr grammar to handle ecl fields named maxlength

wsclient/pom.xml, wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecord.g4, wsclient/src/main/java/org/hpccsystems/ws/client/antlr/EclRecordReader.java, wsclient/src/main/java/org/hpccsystems/ws/client/antlr/ErrorListener.java, wsclient/src/main/java/org/hpccsystems/ws/client/antlr/ErrorStrategy.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUDataColumnInfo.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfo.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/DFURecordDefInfo.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/EclRecordInfo.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/DFUFileDetailInfoTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/RampsDevRegressionTest.java
This fixes the ecl parse issues found in JAPI-114.
As part of the fix I built a regression test that runs against all files on a cluster and parses their record structures. While running this I found a couple more cases of record structures not being handled (layouts and field types starting with "__", and certain nested inline record structures.)
I also added a parseErrors() collection into the EclRecordInfo object generated by the parser to store any parse errors encountered during parsing. This was needed to correctly validate and test the changes.
Expanded DFUFileDetailInfoTest to test for record structures that were previously failing.
I also created a regression test that iterates through all files on a cluster, tests parsing, and logs which files' ecl failed to parse. After my …
=> JAPI-114: fix ecl parsing

wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java, wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFilePartWrapper.java
- Accounts for 1based indexes
- Ensures reported indexes are within bounds
=> JAPI-130 Ensure reported filepart and copy indexes are valid

commons-hpcc/pom.xml, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
Fixes JAPI 184.
Also, I discovered when loading up the latest master that HPCC-commons had a missing/incorrect dependency for log4j preventing the maven compile from working. Updated that pom as part of this PR.
I also updated the cluster info for DFUReadWriteTest to point to a cluster that is currently up and running.
* Updated the DFUReadWriteTest to test reading out projected recordlayouts.
* Ran mvn install and tested the SALT/hpcc code that had previously been failing against the installed dfuclient jar; the SALT/hpcc code worked. All other SALT/hpcc code referencing dfuclient also still worked.
=> JAPI-184: Update HPCCFile to set the projectedrecordlayout when a projectlist is set.

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsDFUClient.java
Tested unit tests, and also tested the compiled jar with the hpcc tardis module.
=> JAPI-208 set default dfufiletype to avoid platform error

wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUCreateFileWrapper.java, wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java
=> JAPI-234 DFUFileAccessInfoWrapper needs to handle null FileType properly

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSTopologyClientTest.java
- Uses correct target cluster names
Created new junit test cases and ran successfully
=> JAPI-251 Fix wstopology getvalidtargetclusters

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsClientTest.java
- Add new method to return available cluster names
- Add test cases for get target clusters, and cluster
=> JAPI-255 Clarify getavailabletargetclusters vs getavailablecluster

wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFileAccessInfoWrapper.java, wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/wsdfu/DFUFilePartWrapper.java
- Ignores last file part report for keyed files
=> JAPI-267 Temporary work-around

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
Created a unit test that tested writing null values for ecl types STRING, BOOLEAN, INTEGER2, INTEGER8,UNSIGNED8, REAL8, DECIMAL5_2, DATA, UTF8, UNICODE and ENUM. Default values ("" for string, false for boolean, 0 for null numerics and enum) were correctly written.
Also reran all other ReadWriteDFUTest use cases.
=> Japi-277 binaryrecordwriter npes

commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FileFilter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSBenchmarkTest.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsAttributesClientIntegrationTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseWsWorkunitsClientIntegrationTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSPackageProcessTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSTopologyClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WUQueryTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsAttributesClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsDFUClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsSMCClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WsWorkunitsClientIntegrationTest_620.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/EclParseRegressionTest.java
- Ensure baseremotetest fields initialized in static block
- No longer re-initialize final static fields in setup method
- FileFilter was swallowing exceptions
- DFSClient's hpccfile was not setting targetfilecluster
=> JAPI-286 Improve RemoteUnitTest performance

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsSQLClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSSQLClientTest.java
- Exercise all executeSQL methods
- Method returning wuid should suppress results
- Decrease response sizes
- Various refactors
=> JAPI-293 Address WsSQL fulltest junit error

dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java, wsclient/src/main/java/org/hpccsystems/ws/client/platform/test/BaseRemoteTest.java
* Create additional constructor for HPCCRemoteFileWriter that takes a connect timeout value
* update current constructor for HPCCRemoteFileWriter to call the new constructor, passing RowServiceOutputWriter.DEFAULT_CONNECT_TIMEOUT_MILLIS
* Create additional constructor for RowServiceOutputWriter that takes a connect timeout value
* update current (non-deprecated) constructor for RowServiceOutputWriter to call the new constructor, passing RowServiceOutputWriter.DEFAULT_CONNECT_TIMEOUT_MILLIS
* update DFSReadWriteTest so that it can run passing a connect timeout value defined as a system property. If no connect timeout is defined, the test runs as it used do with default timeouts specified.
- [] I have applied the Eclipse code-format template provided.
Tested the change by running …
=> JAPI-318 : provide way to define connect timeout when writing files.

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Corrected bug in sign extension code
- Added support for writing int3,int5,int6,int7
- Updated numeric overflow tests for non standard int sizes
=> JAPI-325 BinaryRecordReader not correctly handle integer overflow for non-standard types

dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Changed read behavior to not block on socket
=> JAPI-357 RowServiceInputStream blocks incorrectly on socket

wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/utils/Security.java
- Provides centralized safer Docbuilder helper method
- FileSpray and BaseHPCCWsClient to use new safer doc builder
=> HPCC4J-463 Eliminate External Entity XML parsing

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/FileSprayClientTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/utils/UtilsTest.java
- Provide utilities to ensure trailing slash on a given path string
- Provide junit for ensure trailing slash utility
- Ensure all DZ paths acquired from hpcc >= 7.12.98 contain trailing slash
- Provide DZ path junit
=> HPCC4J-477 Ensure DZ paths contain trailing slash > 7.12.98

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Modified BinaryRecordReader to correctly handle read ahead in varstr
- Added a long string test
=> JAPI-498 DFSClient: Reading long varstrings corrupted

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRecordAccessor.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Fixed BinaryRecordWriter pathways to check for null elements
- Added a new null element test
=> HPCC4J-529 DFSClient: BinaryRecordWriter NPE with null UTF8 strings

dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- Added open / close logging output
=> HPCC4J-537 Log open / close operation info

dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Corrected error handling on prefetch thread to pass errors on startup
- Fixed potential data race in exception handling
- Added invalid signature test
=> HPCC4J-540 Missing file error during publish

dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added file part failure retry test
- Fixed retry issue on initial connection
=> HPCC4J-542 DFSClient: Create JUnit for read retry

dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Updated resume read test to periodically run gc
=> HPCC4J-545 Resume read test causes OOM error

dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java
- Added getter & setter for the useTLK option
=> HPCC4J-551 HPCCFile Make TLK Use Optional

.github/workflows/Jirabot.yml
- Added exception to error output
- Fixed transition array output
=> HPCC4J-532 Jirabot debugging improvements

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/FileUtilityTest.java
- Added support for reading a file without writing it to disk
- Added support for test reading individual file parts
=> HPCC4J-552 File Utility Read Invididual File Parts

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/test/resources/generate-datasets.ecl
- Corrected BinaryRecordReader unsigned decimal parse code
- Updated ECL test datasets to include odd precision decimal values
=> HPCC4J-562 Odd unsigned decimals incorrect scale

.github/workflows/httpsUnitTests.yml, wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- Modified WSFileIOClientTest.copyfile test to correctly monitor spray progress
- Updated remote unit tests values.yaml to keep file spray service
=> HPCC4J-561 copyfile test wait for spray completion

.github/workflows/baremetal-regression-suite.yml, .github/workflows/k8s-regression-suite.yml
- Renamed existing k8s workflow
- Added baremetal workflow
=> HPCC4J-553 Github Actions: Add baremetal test workflow

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordWriter.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Modified BinaryRecordWriter to only truncate strings at EOS in var strings
- Added unit test that verifies read / write all of Unicode chars and mid EOS
=> HPCC4J-569 Correct EOS character handling

.github/workflows/JirabotMerge.yml
=> HCCP4J-571 Github Action: Jirabot Merge fails

.github/workflows/Jirabot.yml, .github/workflows/JirabotMerge.yml
- Moved github user dictionary to github action var
- Changed logic for changing jira issue user
=> HPCC4J-574 Jirabot improvements

dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Changed prefetch thread behavior to short sleep after each request
- Added short sleep on main thread if blocked by prefetch thread for more than 10us
=> HPCC4J-579 prefetch thread hot loop fix

.github/workflows/publish-release-on-merge.yml, .github/workflows/publish-snapshots-on-merge.yml, pom.xml
=> HPCC4J-548 Deployment to jfrog artifactory

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/utils/UtilsTest.java
- Introduces functionality to strip trailing white space
- Adds trimright utility functionality
- Adds new test cases
- Adjusts pre-existing test cases to expected | actual format
- Do not trim original string parameter
- Do not duplicate Path URL param
=> HPCC4J-581 WsFS Client should add path delim only if needed

.github/workflows/Jirabot.yml
- Updated Jirabot to work with current Jira and new Cloud Jira
=> HPCC4J-578 Migrate existing jirabot logic to new Jira environment

dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- Fixed issue where some constructor params were not being passed from overloaded constructors
=> HPCC4J-588 HpccRemoteFileReader doesn't pass constuctor params

dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Modified test to ignore non-defined unicode chars
- Modified test to discard invalid surrogate pairs
- Modified fixed strings to have enough capacity for multi-char codepoints
=> HPCC4J-587 Character handling test failure

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsFileIOClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSFileIOClientTest.java
- Adds new methods with exposed LZ Address
- Provides LZ in non-containerized junits
- Changes default LZ name from localhost to mylandingzone
=> HPCC4J-567 Adapt WsFileIOClient to latest ESP behavior

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsResourcesClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/wrappers/gen/wsresources/HPCCQueueTypeWrapper.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSResroucesClientTest.java
- Adds test cases to account for all wsresources methods
- Adds logic to create HPCCQueueType based on string representation
- Adds all available methods to HPCCWsResourcesClient
=> HPCC4J-590 Add WsResources test cases

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java
- Added Read Retry to HPCCRemoteFileReader
- Minor improvements to FileUtility to improve testing
=> HPCC4J-577 Added Read Retry to HPCCRemoteFileReader

.github/workflows/JAPIPRBuildAction.yml, wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteInitTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteTest.java
- Updated init logic in BaseRemoteTest to automatically fail tests if init fails
=> HPCC4J-599 Halt all JUnits on init failure

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/DataPartition.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsTopologyClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteTest.java
Enhance error logging to help pinpoint future errors more specifically
=> HPCC4J-595 Enhance log messages

dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java, dfsclient/src/test/resources/generate-datasets.ecl
=> HPCC4J-609 DFSReadWriteTest: Increase delimited dataset sizes

wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java, wsclient/src/test/java/org/hpccsystems/ws/client/utils/ConnectionTest.java
- Added explicit check for underscores in hostname
=> HPCC4J-605 Connection: Improve Invalid URL Error Message

pom.xml, wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsWorkUnitsClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Connection.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSWorkunitsTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
=> HPCC-586 Add Otel Tracing support

.github/workflows/Jirabot.yml, .github/workflows/JirabotMerge.yml
- Fixed jirabot merge add fix version code
- Updated transition logic to be less brittle
=> HPCC4J-608 Merge fix version failure

.github/workflows/Jirabot.yml, .github/workflows/JirabotMerge.yml
- Removed code that printed out untrusted information
- Modified curl command to use more secure subprocess module
=> HPCC4J-620 Jirabot: Sanitize information coming from external sources

dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/Utils.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java
- Added tracing support to read pathways
- Added tracing support to write pathways
=> HPCC4J-611 Add OpenTelemetry tracing to dfsclient

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCWsStoreClient.java, wsclient/src/test/java/org/hpccsystems/ws/client/WSStoreClientTest.java
- Adds new WsStore tests based on values which include IPT attribute delimiters
- Fixes issue noticed in wsstoreclient
- Adds ability to test encod-able username
- Adds fetch encoded key test
- Adds fetch invalid key test
=> HPCC4J-614 WsStore IPT invalid character tests

dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Removed incorrect handle read, clarified why reading an additional int is needed during close
=> HPCC4J-624 RowServiceInputStream handle read before close cleanup

wsclient/src/main/java/org/hpccsystems/ws/client/HPCCFileSprayClient.java, wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/utils/UtilsTest.java
- Add util method to append paths
- Add junit test for new methods
- Ensure wsfs methods use new method
=> HPCC4J-630 Ensure Filespray path constructed correctly

wsclient/src/main/java/org/hpccsystems/ws/client/BaseHPCCWsClient.java
- Ensures version response is not HTML based
- Adds relevant message to parsing errors
=> HPCC4J-631 Provide meaningful version error message

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added additional options to FileUtility to help debug bandwidth issues
=> HPCC4J-635 DFSClient: FileUtility add additional testing / debug options

dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCRemoteFileWriter.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceOutputStream.java
- Improved span names
- Transitioned read request events to read spans
- Move events to spans for connect, version and close
- Added span batch support
=> HPCC4J-636 DFSClient: Improve Opentelemetry tracing

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
- Added prompting for credentials if not specified via command line
=> HPCC4J-637 DFSClient: FileUtility add credential prompting

wsclient/src/main/java/org/hpccsystems/ws/client/utils/Utils.java, wsclient/src/test/java/org/hpccsystems/ws/client/BaseRemoteTest.java, wsclient/src/test/java/org/hpccsystems/ws/client/platform/test/PlatformTester.java
- Adds util functions to detect use of otel javaagent
- Adds logic to optionally bypass manual initialization of otelsdk
=> HPCC4J-612 Ensure proper OTel SDK initialization

.github/workflows/JirabotMerge.yml
- Improved tag filtering to find fix versions to support more complex tag structures
=> HPCC4J-638 Jirabot Merge improve tag regex filtering

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
- Fixed false sharing on atomic counter in FileUtility
=> HPCC4J-644 FileUtilityTest atomic record count false sharing

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java
- Added a check to only initialize the OTel autosdk if an OTel javaagent hasn't been set
=> HPCC4J-647 FileUtility only use otel autosdk without javaagent

dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added change to set isTLK option on node object when requesting a read operation on a TLK
=> HPCC4J-646 RowServiceInputStream set isTLK when reading a TLK

.github/workflows/JirabotMerge.yml
- Modified script to allow multiple projects to be controlled from a single script
- Fixed regex warning on escaped characters
=> HPCC4J-651 JirabotMerge: Allow multiple projects to be configured

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Added a limit to the number of connections that can be started simultaneously
- Reduced the size of the initial read request
- Exposed parameters in FileUtility
=> HPCC4J-639 Add concurrent connection startup limit

commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldDef.java, commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/HpccSrcType.java, commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/RecordDefinitionTranslator.java, commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/TestFieldDefinitions.java, commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/RecordDefinitionTests.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/ColumnPruner.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java
- Modified record translation code to maintain integer subtype
- Fixed record translation test case
- Added index record translation to test case
=> HPCC4J-650 DFSClient should retain integer subtypes

commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/FieldDef.java, commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/RecordDefinitionTranslator.java, commons-hpcc/src/main/java/org/hpccsystems/commons/ecl/TestFieldDefinitions.java, commons-hpcc/src/test/java/org/hpccsystems/commons/ecl/RecordDefinitionTests.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/HPCCFile.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSIndexTest.java, dfsclient/src/test/resources/generate-datasets.ecl
- Updated RecordDefinitionTranslator to maintain blob information
- Added isBlob property to FieldDef
- Added translation test for indices with blobs
- Added index read test for indices with blobs
- Updated data generation to create an index with blobs
=> HPCC4J-657 DFSClient: Reading indices with blobs fails

dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Changed RowServiceInputStream to use the active span instead of the top level read span for the traceparent on requests
=> HPCC4J-667 DFSClient: Request traceparents should use active span

dfsclient/src/main/java/org/hpccsystems/dfs/client/FileUtility.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/FileUtilityTest.java
- Added a non-interactive flag to FileUtility
- Updated FileUtilityTest to use the non-interactive flag
=> HPCC4J-642 DFSClient FileUtilityTest failing due to credential prompting

dfsclient/src/main/java/org/hpccsystems/dfs/client/ColumnPruner.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSHPCCFile.java
- Updated ColumnPruner to correctly clone child field defs
=> HPCC4J-691 DFSClient: Column pruner should clone field defs

dfsclient/src/main/java/org/hpccsystems/dfs/client/BinaryRecordReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/CircularByteBuffer.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/CircularByteBufferTest.java
- Created new CircularByteBuffer class
- Created CircularByteBufferTest
- Made changes to allow read buffer size to be smaller than the read request size
=> HPCC4J-606 DFSClient Allow ReadBuffer size to be set

dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java, dfsclient/src/test/java/org/hpccsystems/dfs/client/DFSReadWriteTest.java
- Added missing read buffer size option in the read context
- Added missing check to make sure readBufferSize > 0
=> HPCC4J-696 DFSClient expose read buffer size setting

dfsclient/src/main/java/org/hpccsystems/dfs/client/HpccRemoteFileReader.java, dfsclient/src/main/java/org/hpccsystems/dfs/client/RowServiceInputStream.java
- Fixed issue where read resume could duplicate a record when restart occurs along a fetch boundary
- Added code to put a cap on the fetch history size
=> HPCC4J-687 DFSClient read resume test failure
